.catalog:
  name: "Consul"
  description: "Secure Consul cluster"
  version: "1.3.0-rancher2"
  uuid: consul-0
  questions:
    - variable: ca_crt
      label: "CA certificate"
      type: "multiline"
      required: true
    - variable: consul_key
      label: "consul key"
      type: "multiline"
      required: true
    - variable: consul_crt
      label: "consul certificate"
      type: "multiline"
      required: true
    - variable: gossip_key
      label: "Communication gossip key"
      type: "multiline"
      required: true
    - variable: enable_acl
      label: "ACL Access"
      type: "boolean"
      required: true
      default: false
    - variable: acl_default_policy
      label: "ACL Default Policy"
      type: "enum"
      options:
        - "allow"
        - "deny"
      default: "allow"
      required: true
    - variable: acl_down_policy
      label: "ACL Down Policy"
      type: "enum"
      options:
        - "allow"
        - "deny"
      default: "allow"
      required: true
    - variable: acl_master_token
      label: "ACL Master Token"
      type: "string"
      default: ""
      required: false
    - variable: ui
      label: "Enable UI"
      type: "boolean"
      default: false
      required: true
    - variable: bootstrap_expect
      label: "bootstrap expect"
      type: "int"
      default: 3
      required: true
consul:
  scale: 3
  metadata:
    ca.crt: |
            ${ca_crt}
    consul.crt: |
            ${consul_crt}
    consul.key: |
            ${consul_key}
    enc.key: "${gossip_key}"
    acl.enabled: "${enable_acl}"
    acl.default_policy: "${acl_default_policy}"
    acl.down_policy: "${acl_down_policy}"
    acl.master_token: "${acl_master_token}"
    ui.enabled: ${ui}
    bootstrap_expect: ${bootstrap_expect}