.catalog:
  name: "Consul"
  description: "Secure Consul cluster"
  version: "1.4.2-rancher2"
  uuid: consul-0
  questions:
    - variable: ui
      label: "Enable UI"
      type: "boolean"
      default: false
      required: true
    - variable: bootstrap_expect
      label: "bootstrap expect"
      type: "int"
      default: 3
      required: true
consul:
  scale: 3
  metadata:
    ui.enabled: ${ui}
    bootstrap_expect: ${bootstrap_expect}